site_name: Demo Guide
site_url: https://workshop.thyintresources.com/demoguide/
dev_addr: '127.0.0.1:8005'
theme:
  name: material
  
  font:
    text: Manrope
    code: Manrope
  
  logo: img/Delinea.svg
  
  favicon: img/favicon.ico
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - search.highlight

plugins:
  - search
  - with-pdf:
      author: Delinea Technical Enablement
      cover_title: Demo Guide
      cover_subtitle:  Sercret Server, Privilege Manager, and Server PAM
      cover_logo: img/secretserver.jpg
      copyright: Delinea
      enabled_if_env: ENABLE_PDF_EXPORT
      debug_html: false

extra:
  generator: false

nav:
  - Home: index.md
  - Secret Server:
    - Introduction: secretserver/mod1/mod1.md
    - General Use Case: secretserver/mod2/mod2.md
    - Privileged Launching use case: secretserver/mod3/mod3.md
    - Advanced use case: secretserver/mod4/mod4.md
  - Privilege Manager:
    - Introduction: privman/mod1/mod1.md
    - Application control use cases: privman/mod2/mod2.md
    - Local user/group Management use case: privman/mod3/mod3.md
    - Reporting use cases: privman/mod4/mod4.md
  - Server PAM:
    - Active Directory (AD) Bridging: srvpam/mod1/mod1.md
    - Just-In-Time (JIT) Privileges: srvpam/mod2/mod2.md
    - Security logs: srvpam/mod3/mod3.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences